name: Auto Comment

on: [issues, pull_request]

jobs:

  run:

    runs-on: ubuntu-latest

    steps:

      - uses: wow-actions/auto-comment@v1

        with:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          issuesOpened: |

            # 👋 @{{ author }}. It's great having you contribute to Memories 🎉 !

            Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.

            Meanwhile feel free to support star the repo and share it with your friends. 🤓 🚀

          pullRequestOpened: |

            # Hey @{{ author }}. Thank you for raising your pull request!

            Please make sure you have followed our contributing guidelines. We will review it as soon as possible.

            **Star ✨ other repositories [here](https://github.com/warmachine028)**

            

            **Happy Hacking!! 🌠**
